name: Continuous Integration

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Test (Python ${{ matrix.python }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.7", "3.8", "3.9", "3.10"]
    container:
      image: python:${{ matrix.python }}
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: Commit Linter
        uses: wagoid/commitlint-github-action@v4
      - id: install
        name: Install requirements
        run: |
          pip install clinner pip poetry --upgrade
          ./scripts/install
      - id: black
        name: Code format checking
        run: ./scripts/black --check .
      - id: isort
        name: Imports order checking
        run: ./scripts/isort --check .
      - id: flake8
        name: Code style (flake8)
        run: ./scripts/flake8
      - id: mypy
        name: Static types check
        run: ./scripts/mypy
      - id: tests
        name: Tests
        run: ./scripts/test
      - id: codecov
        name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.0.2
        # Run on a specific python version and only master branch commits
        if: matrix.python == 3.9 && github.event_name == 'push' && github.ref == 'refs/heads/master'
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: test-results/coverage.xml
  release:
    needs: test
    name: Release a new version
    runs-on: ubuntu-latest
    container:
      image: perdy/github-actions-builder:latest
    steps:
      - uses: actions/checkout@master
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - id: publish
        name: Publish version
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_ACTIONS_TOKEN }}
          PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
