name: Docker Push

on:
  push:
    tags:
      - 'v*'

env:
  DEFAULT_LINUX: "slim"
  DEFAULT_PYTHON: "3.11"

jobs:
  docker_push:
    name: Docker Push (${{ matrix.linux }}, ${{ matrix.python }})
    environment:
      name: dockerhub
      url: https://hub.docker.com/r/perdy/flama
    runs-on: ubuntu-latest
    strategy:
      matrix:
        linux: ["slim"]
        python: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    steps:
      - name: Check out the repo
        uses: actions/checkout@master
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/flama
          flavor: |
            latest=false
          tags: |
            type=semver,enable=true,pattern=${{ matrix.linux }}-{{version}}-python${{ matrix.python }}
            type=semver,enable=true,pattern=${{ matrix.linux }}-latest-python${{ matrix.python }}
            type=semver,enable=${{ matrix.python == env.DEFAULT_PYTHON && 'true' || 'false' }},pattern=${{ matrix.linux }}-{{version}}
            type=semver,enable=${{ matrix.python == env.DEFAULT_PYTHON && 'true' || 'false' }},pattern=${{ matrix.linux }}-latest
            type=semver,enable=${{ matrix.linux == env.DEFAULT_LINUX && 'true' || 'false' }},pattern={{version}}-python${{ matrix.python }}
            type=semver,enable=${{ matrix.linux == env.DEFAULT_LINUX && 'true' || 'false' }},pattern=latest-python${{ matrix.python }}
            type=semver,enable=${{ matrix.python == env.DEFAULT_PYTHON && (matrix.linux == env.DEFAULT_LINUX && 'true' || 'false') || 'false' }},pattern=latest
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          build-args: |
            PYTHON_VERSION=${{ matrix.python }}
          context: Dockerfiles/${{ matrix.linux }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
