name: Publish Docs

on:
  push:
    branches:
      - master

jobs:
  docs:
    name: Update docs
    runs-on: ubuntu-latest
    container:
      image: perdy/github-actions-builder:latest
    steps:
      - uses: actions/checkout@master
      - id: install
        name: Install requirements
        run: python make install
      - id: build_docs
        name: Update docs
        run: |
          git config user.name "José Antonio Perdiguero López"
          git config user.email "perdy@perdy.io"
          git remote set-url origin "https://${{ secrets.GITHUB_ACTIONS_TOKEN }}@github.com/${{ github.repository }}.git"
          ./scripts/docs gh-deploy -m "[skip ci] Deployed {sha} with MkDocs version: {version}" --force