name: Test And Publish

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'examples/**'
      - '.github/**'
      - 'docs/**'
      - 'scripts/**'

env:
  DEFAULT_LINUX: "slim"
  DEFAULT_PYTHON: "3.11"

jobs:
  test:
    name: Test (${{ matrix.python }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [ "3.7", "3.8", "3.9", "3.10", "3.11"]
    container:
      image: python:${{ matrix.python }}
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: Commit Linter
        uses: wagoid/commitlint-github-action@v5
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - id: install
        name: Install requirements
        run: |
          pip install pip poetry --upgrade
          ./scripts/install
      - id: black
        name: Code format checking
        run: ./scripts/black --check .
      - id: isort
        name: Imports order checking
        run: ./scripts/isort --check .
      - id: ruff
        name: Code style (ruff)
        run: ./scripts/ruff .
      - id: mypy
        name: Static types check
        run: ./scripts/mypy .
      - id: tests
        name: Tests
        run: ./scripts/test
      - id: codecov
        name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.0.2
        # Run on a specific python version and only master branch commits
        if: matrix.python == env.DEFAULT_PYTHON && github.event_name == 'push' && github.ref == 'refs/heads/master'
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: test-results/coverage.xml
  release:
    needs: test
    name: Release a new version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.publish.outputs.new_release_version }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@master
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Setup poetry
        run: pip install pip poetry --upgrade
      - id: publish
        name: Publish version
        uses: cycjimmy/semantic-release-action@v3
        with:
          extra_plugins: |
            semantic-release-gitmoji@1.5.0
            @semantic-release/changelog
            @semantic-release/exec
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
  docker_push:
    name: Docker Push (${{ matrix.linux }}, ${{ matrix.python }}, ${{ matrix.schemas }})
    needs: release
    environment:
      name: dockerhub
      url: https://hub.docker.com/r/perdy/flama
    runs-on: ubuntu-latest
    strategy:
      matrix:
        linux: ["slim"]
        python: ["3.7", "3.8", "3.9", "3.10", "3.11"]
        schemas: ["pydantic", "marshmallow", "typesystem"]
    steps:
      - name: Check out the repo
        uses: actions/checkout@master
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/flama
          flavor: |
            latest=false
          tags: |
            type=raw,enable=true,value=${{ matrix.linux }}-${{ needs.publish.outputs.version }}-python${{ matrix.python }}-${{ matrix.schemas }}
            type=raw,enable=true,value=${{ matrix.linux }}-latest-python${{ matrix.python }}-${{ matrix.schemas }}
            type=raw,enable=${{ matrix.python == env.DEFAULT_PYTHON && 'true' || 'false' }},value=${{ matrix.linux }}-${{ needs.publish.outputs.version }}-${{ matrix.schemas }}
            type=raw,enable=${{ matrix.python == env.DEFAULT_PYTHON && 'true' || 'false' }},value=${{ matrix.linux }}-latest-${{ matrix.schemas }}
            type=raw,enable=${{ matrix.linux == env.DEFAULT_LINUX && 'true' || 'false' }},value=${{ needs.publish.outputs.version }}-python${{ matrix.python }}-${{ matrix.schemas }}
            type=raw,enable=${{ matrix.linux == env.DEFAULT_LINUX && 'true' || 'false' }},value=latest-python${{ matrix.python }}-${{ matrix.schemas }}
            type=raw,enable=${{ matrix.python == env.DEFAULT_PYTHON && (matrix.linux == env.DEFAULT_LINUX && 'true' || 'false') || 'false' }},value=latest-${{ matrix.schemas }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          build-args: |
            PYTHON_VERSION=${{ matrix.python }}
            SCHEMAS_LIB=${{ matrix.schemas }}
          context: Dockerfiles/${{ matrix.linux }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
